version: 3

vars:
  name: "fwatcher"

tasks:
  dev:
    cmds:
      - go run ./cmd

  build:
    requires:
      vars:
        - version
    vars:
      upx: '{{.upx | default "false"}}'
      binary: '{{.binary | default .name }}'
      date_str:
        sh: "date '+%T %p (%Z) | %a %b %d, %Y'"
      version_str: "[{{.version }}] built at {{.date_str}}"
    env:
      GOOS: '{{ .GOOS }}'
      GOARCH: '{{ .GOARCH }}'
    cmds:
      - echo "building binary for ${GOOS:-$(go env GOOS)} (${GOARCH:-$(go env GOARCH)})"
      - echo version str "{{.version_str}}"
      - go build -ldflags '-s -w -X "main.Version={{.version_str}}"' -o ./bin/{{.binary}} ./cmd
      - |+
        if [[ "{{.upx}}" = "true" ]]; then
          upx ./bin/{{.binary}}
        fi

  test:executor:
    cmds:
      - go test ./pkg/executor/...

  build:dev:
    cmds:
      - go build -o ./bin/fwatcher ./cmd

  example:http-server:
    cmds:
      - |+
        go run ./examples/http-server/main.go

  install:
    cmds:
      - task: build
        vars:
          version: dev
      - ln -sf $PWD/bin/{{.name}} $HOME/.local/bin/{{.name}}
