version: 3

vars:
  name: "fwatcher"

tasks:
  dev:
    cmds:
      - go run .

  dev:build:
    cmds:
      - go build -ldflags "-s -w -X main.Version={{.version}}" -o ./bin/{{.name}}

  build:
    requires:
      vars:
        - version
    vars:
      upx: '{{.upx | default "false"}}'
      binary: '{{.binary | default .name }}'
    env:
      GOOS: '{{ .GOOS }}'
      GOARCH: '{{ .GOARCH }}'
    cmds:
      - echo "building binary for ${GOOS:-$(go env GOOS)} (${GOARCH:-$(go env GOARCH)})"
      - go build -ldflags "-s -w -X main.Version={{.version}}" -o ./bin/{{.binary}}
      - |+
        if [[ "{{.upx}}" = "true" ]]; then
          upx ./bin/{{.binary}}
        fi

  example:http-server:
    cmds:
      - task: dev:build
      - |+
        {{.Bin}} --debug  --ext '.go' --exec 'go run ./examples/http-server/main.go'

  install:
    cmds:
      - task: build
        vars:
          version: dev
      - ln -sf $PWD/bin/{{.name}} $HOME/.local/bin/{{.name}}
